### ISSUE TITLE
add sidebar animations

### ISSUE THREAD

**Issue by 1p22geo** [1p22geo/strona#1]

**Comment by TNTErick** [comment]
Can you explain a lil bit more?

**Comment by 1p22geo** [comment]
Who are you?

**Comment by 1p22geo** [comment]
No, pls don't get me wrong, I don't mind other people in my repo but seriously: what are you doing in my school project? How did you get here

**Comment by 1p22geo** [comment]
Also, it's about the sidebar hiding and showing after pressing a button
